
FROM node:23-alpine

WORKDIR /usr/app

COPY package*.json .

RUN npm install

COPY . .

#EXPOSE 3000

#host allow other computers connect to this development server
CMD ["npm", "run", "dev", "--", "--host"]
