apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multi-k8s.juanmiguel431-com-tls
spec:
  secretName: multi-k8s.juanmiguel431-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.juanmiguel431.com
  dnsNames:
    - multi-k8s.juanmiguel431.com
    - www.multi-k8s.juanmiguel431.com
